[package]
name = "marloth_automation_proto"
version.workspace = true
edition.workspace = true
description = "Protobuf/gRPC types for Marloth Godot automation"
license.workspace = true

[dependencies]
prost = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
protoc-bin-vendored = "3"
